language: java
sudo: required
jdk: oraclejdk8
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.org#selenium"
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TASK=build
    - TASK=rb TARGET=unit-test
    - TASK=rb TARGET=firefox-test
    - TASK=rb TARGET=firefox-test
    - TASK=rb TARGET=phantomjs-test
    - TASK=rb TARGET=chrome-test
    - TASK=py TOXENV=py27-chrome
    - TASK=py TOXENV=py27-firefox
    - TASK=py TOXENV=py27-marionette
    - TASK=py TOXENV=py27-phantomjs
matrix:
  fast_finish: true
  allow_failures:
    - env: TASK=rb TARGET=unit-test
    - env: TASK=rb TARGET=firefox-test
    - env: TASK=rb TARGET=firefox-test
    - env: TASK=rb TARGET=phantomjs-test
    - env: TASK=rb TARGET=chrome-test
    - env: TASK=py TOXENV=py27-chrome
    - env: TASK=py TOXENV=py27-firefox
    - env: TASK=py TOXENV=py27-marionette
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - |
      if [[ $TARGET+$TOXENV == *"chrome"* ]]; then
        export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
        curl -L -o chrome.zip "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
        unzip chrome.zip
        export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        curl -L -o chromedriver.zip "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
      fi
  - |
      if [[ $TOXENV == *"marionette"* ]]; then
        export GECKODRIVER_VERSION=v0.10.0
        curl -L -o geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        gunzip -c geckodriver.tar.gz | tar xopf -
        chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
        apt-get -y purge firefox
        wget -O /tmp/firefox.tar.bz2 https://download.mozilla.org/?product=firefox-latest&lang=en-US&os=linux64
        tar xf /tmp/firefox.tar.bz2
        sudo ln -sf firefox/firefox /usr/local/bin/firefox
      fi
  - |
      if [[ $TARGET+$TOXENV == *"phantomjs"* ]]; then
        export PHANTOMJS_NAME=phantomjs-2.1.1-linux-x86_64
        curl -L -O "https://cnpmjs.org/mirrors/phantomjs/${PHANTOMJS_NAME}.tar.bz2"
        tar -xvjf $PHANTOMJS_NAME.tar.bz2
        chmod +x $PHANTOMJS_NAME/bin/phantomjs
      fi
  - |
      if [[ $TASK == "build" ]]; then
        ./go build
      fi
  - |
      if [[ $TASK == "py" ]]; then
        ./go py_prep_for_install_release
        pip install --user tox-travis
        tox
      fi
  - |
      if [[ $TASK == "rb" ]]; then
        rvm install 2.2.3
        rvm use 2.2.3
        ./go //rb:$TARGET
      fi
